language: python
python:
  - "3.6.4"

install:
  - pip install -r requirements.txt

script:
  - python3 manage.py test --settings=authors.settings.test

after_success:
  - coveralls

env:
  - SECRET_KEY='7pgozr2jn7zs_o%i8id6=rddieSECRET_KEY0f0qy3$oy$(8231i^4*@u3'

