# Generated by Django 2.0.6 on 2018-08-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180730_1844'),
        ('authentication', '0003_auto_20180731_1453'),
    ]

    operations = [
    ]
