# Generated by Django 2.0.6 on 2018-08-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_merge_20180802_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_account_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
