# Generated by Django 2.0.6 on 2018-08-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_account_verfied'),
        ('authentication', '0004_merge_20180801_1857'),
    ]

    operations = [
    ]
