# Generated by Django 2.0.6 on 2018-08-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_social_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.IntegerField(db_index=True, default=0, max_length=255, unique=True),
        ),
    ]
