# Generated by Django 2.0.6 on 2018-08-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20180804_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.BigIntegerField(db_index=True, default=0, unique=True),
        ),
    ]
