# Generated by Django 2.0.6 on 2018-08-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_is_account_verfied'),
        ('authentication', '0010_auto_20180804_1549'),
    ]

    operations = [
    ]
