# Generated by Django 2.0.6 on 2018-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_merge_20180806_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_account_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
