# Generated by Django 2.0.6 on 2018-08-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_is_account_verfied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_account_verfied',
        ),
    ]
