# Generated by Django 2.0.6 on 2018-08-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180808_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
