# Generated by Django 2.0.6 on 2018-08-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='body',
        ),
    ]
