# Generated by Django 2.0.6 on 2018-08-09 12:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0009_chilecomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChileComment',
            new_name='ChildComment',
        ),
    ]
