# Generated by Django 2.0.6 on 2018-08-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_articlefavourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlefavourites',
            old_name='is_favourited',
            new_name='is_favourite',
        ),
    ]
