# Generated by Django 2.0.6 on 2018-08-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20180814_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlefavourites',
            old_name='is_favourite',
            new_name='article_favourite',
        ),
    ]
