# Generated by Django 2.0.6 on 2018-08-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20180816_0352'),
        ('articles', '0014_auto_20180814_1409'),
    ]

    operations = [
    ]
