# Generated by Django 2.0.6 on 2018-08-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20180816_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
