# Generated by Django 2.0.6 on 2018-08-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_remove_article_author'),
        ('articles', '0015_merge_20180816_0810'),
    ]

    operations = [
    ]
