# Generated by Django 2.0.6 on 2018-08-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_merge_20180816_1210'),
        ('articles', '0016_auto_20180816_1722'),
    ]

    operations = [
    ]
